- name: "variables from file"
  hosts:  "local"
  connection:  "local"
  vars_prompt:
  - name: COURSE
    prompt: "Please Enter the Course Name"
  
  - name: DURATION
    prompt: "Please Enter the Duration"

  - name: TRAINER
    prompt: "Please Enter the Trainer Name"
  - course.yaml
  
  tasks:
  - name: "print course information"
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }} with AWS, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"