- name: check value is greater than 10 or not
  hosts: local
  connection: local
  vars:
    my_num: 10
  tasks:
  - name: print if your number is greater than 5
    ansible.builtin.debug:
      msg: "Given Number is greater than 5"
    when: my_num > 5
  
  - name:
    ansible.builtin.debug:
      msg: "Given number is lessthan 10"
    when: my_num <= 5
