- name: filters
  hosts: local
  connection: local
  tasks:
  - name: handle undefined variable
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh')}}"


  - name: convert string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
        msg: "Fruits are: {{ fruits | split(',') }}"

  - name: convert map to list
    vars:
      course: 
        name: Devops
        duration: 120hrs
        trainer: siva
    ansible.builtin.debug:
      msg: "Course are: {{ course | dict2items }}"

  - name: convert list to map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value':  '120hrs'}
      - {'key': 'trainer', 'value': 'siva'}
    ansible.builtin.debug:
      msg: "Courses are: {{ course | items2dict }}"
