- name: shell vs command
  hosts: local
  connection: local
  tasks:
  - name: execute ls command
    #ansible.builtin.command: ls -ltr > /tmp/output.txt
    ansible.builtin.shell: ls -ltr > /tmp/output.txt

  - name: execute ls command
    ansible.builtin.command: ls -ltr 
    register: command_result

  - name: print the stored output
    ansible.builtin.debug:
      msg: "{{ command_result }}"






      {
        "msg": {
        "changed": true,
        "cmd": [
            "ls",
            "-ltr"
        ],
        "delta": "0:00:00.005620",
        "end": "2025-01-14 14:58:02.991709",
        "failed": false,
        "msg": "",
        "rc": 0,
        "start": "2025-01-14 14:58:02.986089",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "total 136\n-rw-r--r-- 1 ec2-user ec2-user   271 Jan 14 11:01 07-vars-file.yaml\n-rw-r--r-- 1 ec2-user ec2-user   489 Jan 14 11:01 06-task-vars.yaml\n-rw-r--r-- 1 ec2-user ec2-user   293 Jan 14 11:01 05-vars.yaml\n-rw-r--r-- 1 ec2-user ec2-user   293 Jan 14 11:01 04-multi-play.yaml\n-rw-r--r-- 1 ec2-user ec2-user   283 Jan 14 11:01 03-nginx.yaml\n-rw-r--r-- 1 ec2-user ec2-user   125 Jan 14 11:01 02-hello-world.yaml\n-rw-r--r-- 1 ec2-user ec2-user    86 Jan 14 11:01 01-playbook.yaml\n-rw-r--r-- 1 ec2-user ec2-user   237 Jan 14 11:01 09-vars-inventory.yaml\n-rw-r--r-- 1 ec2-user ec2-user   490 Jan 14 11:01 08-vars-prompt.yaml\n-rw-r--r-- 1 ec2-user ec2-user    81 Jan 14 11:01 course.yaml\n-rw-r--r-- 1 ec2-user ec2-user   357 Jan 14 11:01 14-conditions.yaml\n-rw-r--r-- 1 ec2-user ec2-user   590 Jan 14 11:01 13-data-types.yaml\n-rw-r--r-- 1 ec2-user ec2-user   365 Jan 14 11:01 12-vars-preferences\n-rw-r--r-- 1 ec2-user ec2-user   233 Jan 14 11:01 11-vars-args.yaml\n-rw-r--r-- 1 ec2-user ec2-user   211 Jan 14 11:01 10-vars-inventory.yaml\n-rw-r--r-- 1 ec2-user ec2-user   195 Jan 14 11:12 inventory.ini\n-rw-r--r-- 1 ec2-user ec2-user   128 Jan 14 11:29 15-facts.yaml\n-rw-r--r-- 1 ec2-user ec2-user   339 Jan 14 12:48 16-conditions.yaml\n-rw-r--r-- 1 ec2-user ec2-user 41789 Jan 14 12:48 facts.json\n-rw-r--r-- 1 ec2-user ec2-user   186 Jan 14 12:58 17-loops.yaml\n-rw-r--r-- 1 ec2-user ec2-user   216 Jan 14 13:05 18-loops.yaml\n-rw-r--r-- 1 ec2-user ec2-user   349 Jan 14 13:19 19-loops.yaml\n-rw-r--r-- 1 ec2-user ec2-user  1543 Jan 14 14:31 20-filters.yaml\n-rw-r--r-- 1 ec2-user ec2-user   405 Jan 14 14:57 21-shell-command.yaml",
        "stdout_lines": [
            "total 136",
            "-rw-r--r-- 1 ec2-user ec2-user   271 Jan 14 11:01 07-vars-file.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   489 Jan 14 11:01 06-task-vars.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   293 Jan 14 11:01 05-vars.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   293 Jan 14 11:01 04-multi-play.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   283 Jan 14 11:01 03-nginx.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   125 Jan 14 11:01 02-hello-world.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user    86 Jan 14 11:01 01-playbook.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   237 Jan 14 11:01 09-vars-inventory.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   490 Jan 14 11:01 08-vars-prompt.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user    81 Jan 14 11:01 course.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   357 Jan 14 11:01 14-conditions.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   590 Jan 14 11:01 13-data-types.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   365 Jan 14 11:01 12-vars-preferences",
            "-rw-r--r-- 1 ec2-user ec2-user   233 Jan 14 11:01 11-vars-args.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   211 Jan 14 11:01 10-vars-inventory.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   195 Jan 14 11:12 inventory.ini",
            "-rw-r--r-- 1 ec2-user ec2-user   128 Jan 14 11:29 15-facts.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   339 Jan 14 12:48 16-conditions.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user 41789 Jan 14 12:48 facts.json",
            "-rw-r--r-- 1 ec2-user ec2-user   186 Jan 14 12:58 17-loops.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   216 Jan 14 13:05 18-loops.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   349 Jan 14 13:19 19-loops.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user  1543 Jan 14 14:31 20-filters.yaml",
            "-rw-r--r-- 1 ec2-user ec2-user   405 Jan 14 14:57 21-shell-command.yaml"
        ]
    }
}


    