- name: create ec2 and r53 records
  connection: local
  hosts: local
  vars:
    subnet_id: subnet-0345aeff448f7651a
    sg_id: sg-02f988de9e2552a2d
    ami_id: ami-09c813fb71547fc4f
    instance_type: t3.micro
    instances:
    - mysql
    - backend
    - frontend
  tasks:
  - name: Install Aws python lybraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - boto3
    - botocore

  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      subnet_id: "{{ subnet_id }}"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      instance_type: "{{ instance_type }}"
    loop: "{{ instances }}"
    register: ec2_info

  - name: print ec2_info
    ansible.builtin.debug:
      msg: "{{ ec2_info }}"
